### ISSUE TITLE
cargo: consider setting panic=abort in the release profile

### ISSUE THREAD

**Issue by csssuf** [coreos/afterburn#107]
# Feature Request #

## Environment ##
All.

## Desired Feature ##
Building release binaries with `panic=abort` reduces their size by a considerable amount, which would make including `coreos-metadata` in the initramfs more palatable. However, it might interfere with some cleanup behavior we are currently relying on with `panic=unwind`.

## Other Information ##
See #105 for the original discussion.

**Comment by prestist** [comment]
Currently we are shipping other bin's which are much larger, while this could be shrunk down, currently there are other bins which would be better to be focused on.
