### ISSUE TITLE
Drop merging of authorized_keys.d into authorized_keys

### ISSUE THREAD

**Issue by bgilbert** [coreos/afterburn#157]
# Feature Request #

## Environment ##

Any

## Desired Feature ##

At present, `coreos-metadata --ssh-keys` implicitly assumes that [update-ssh-keys](https://github.com/coreos/update-ssh-keys) is distributed as part of the OS.  That is, it assumes that SSH keys should be written into `~/.ssh/authorized_keys.d/<file>`, and then all files in `authorized_keys.d` should be merged into `authorized_keys`.  On distros without update-ssh-keys, this model doesn't immediately cause problems: coreos-metadata writes `~/.ssh/authorized_keys.d/coreos-metadata` and then performs the sync via an embedded copy of the update-ssh-keys library.  However, if the user updates `authorized_keys` directly and reboots, and `coreos-metadata --ssh-keys` runs again, it will clobber changes to `authorized_keys`.  Instead, the user is expected to put their keys in e.g. `~/.ssh/authorized_keys.d/my-keys`, but then doesn't have a tool to perform the synchronization.

Ultimately, update-ssh-keys is a hack for supporting `authorized_keys.d` directories without any cooperation from sshd, and should be dropped.  It changes the workflow of updating SSH keys and isn't used on other distros; Fedora CoreOS and Red Hat CoreOS currently do not intend to ship it.  Instead, in the short term, Fedora CoreOS will have special-case support for `authorized_keys.d` files written by individual tools, and in the medium term it will add generic support for the key directory (https://github.com/coreos/fedora-coreos-tracker/issues/139#issuecomment-459073242).

Modify coreos-metadata as follows:
- [x] After writing the `authorized_keys.d` fragment file, don't merge the fragment file into `authorized_keys` except on CL.  Probably gate this on a compile-time flag.
- [x] Document that `coreos-metadata --ssh-keys` will only work on distros that include `.ssh/authorized_keys.d/coreos-metadata` in sshd's `AuthorizedKeysFile`, or that otherwise arrange to read all keyfiles in `.ssh/authorized_keys.d`.

**Comment by mikeweilgart** [comment]
> Ultimately, update-ssh-keys is a hack for supporting authorized_keys.d directories without any cooperation from sshd, and should be dropped.

Incidentally, from the sshd_config documentation, I believe it would be *possible* to configure `AuthorizedKeysCommand` (and `AuthorizedKeysCommandUser`) to some shell command that would run `cat ~user/.ssh/authorized_keys.d/*`.

I don't think that's a good idea, mind you.  But when I found the `authorized_keys.d` directory in CoreOS, the first place I went was the ssh and sshd documentation, and the second place was `sshd_config` where I half *expected* to find a shell command as described above.
