### ISSUE TITLE
docs/release-guide: move to checklist ticket template

### ISSUE THREAD

**Issue by lucab** [coreos/afterburn#176]
On each release we publish a `.crate` file to crates.io, which is then used by distribution to package coreos-metadata. Its SHA256 is recorded at publish time in the index, eg 
https://github.com/rust-lang/crates.io-index/commit/e0bc5cf11001a1e79521f3fb21d568d2c50fed42.

In order to improve the integrity chain and to make manual checks easier, we should also record the SHA256 of the `.crate` file on local filesystem (before upload) and publish it in the release notes.

As per discussion with @ashcrow.

**Comment by lucab** [comment]
Also, @bgilbert suggested to convert/augment with a checklist like https://github.com/coreos/ignition/blob/master/.github/ISSUE_TEMPLATE/release-checklist.md

**Comment by lucab** [comment]
Self-note: local digests come from
```
sha256sum target/package/afterburn-${RELEASE_VER}.crate
sha256sum target/afterburn-${RELEASE_VER}-vendor.tar.gz 
```

**Comment by ashcrow** [comment]
The sha256sum's are in the release docs https://github.com/coreos/afterburn/blob/master/docs/release-guide.md#6-assemble-vendor-tarball-and-publish-a-release

**Comment by lucab** [comment]
I'm keeping this ticket open till the guide is actually converted into a checklist ticket template.
