### ISSUE TITLE
Azure: doesn't set hostname

### ISSUE THREAD

**Issue by serbrech** [coreos/afterburn#197]
# Bug #  
Afterburn does not set the hostname on Azure.
## Operating System Version ##  
RHCOS
## Afterburn Version ##  
master
## Environment ##  
Azure

## Expected Behavior ##
`/etc/hostname` contains the machine name defined on Azure
## Actual Behavior ##
no file

## Other Information ##
`curl http://169.254.169.254/metadata/instance/compute/name?api-version=2017-08-01&format=text` gives you the hostname

file location should be `/etc/hostname`

Currently Azure provider returns `None`: 
https://github.com/coreos/afterburn/blob/7db2aff2274ccf7439e4b85d5d944c4f90e807bf/src/providers/azure/mod.rs#L413-L415

**Comment by serbrech** [comment]
@jpang @imcleod @awesomenix

**Comment by lucab** [comment]
I seem to remember the Azure DHCP is able to hand out the hostname to a node via DHCP (Option-12, possibly), which would be the reason why Afterburn doesn't have to take care of that.

Is either the DCHP client not asking/handling that option, or the server not providing it?

**Comment by bgilbert** [comment]
I tried it, and Azure DHCP apparently is not sending the hostname when requested to.  On Container Linux I think WALinuxAgent is setting the hostname.  So implementing in Afterburn and running that in the initramfs seems like the right approach.

**Comment by lucab** [comment]
Then I was mixing up with some other cloud provider, and we have indeed to add such logic to Afterburn.

While I didn't see a JSON schema for the metadata response, there are comprehensive examples and docs at https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#getting-more-information-about-the-vm-during-support-case. As we don't care about other properties in there for the moment, the individual textual-format field is probably a better target to consume.

For completeness, this seems to cover host name only (not node FQDN).
