### ISSUE TITLE
Add Daemon Mode

### ISSUE THREAD

**Issue by ashcrow** [coreos/afterburn#228]
# Feature Request #

Create a daemon mode for afterburn for clouds where having a reactive/scheduled pattern makes sense instead of oneshot runs.

## Environment ##
TBD

## Desired Feature ##

Allow specific providers to have a daemon mode which runs consistently and reacts to specific changes.

## Other Information ##
@darkmuggle has done some initial plumbing work.

**Comment by lucab** [comment]
This is a quite big architectural change, which for the moment we are not undertaking.

The main rationale is that we are on purpose not trying to re-implement an omni-cloud all-encompassing daemon agent, but instead breaking apart common functionality in single one-short verbs.

If we ever start doing down that route, there are a few pre-requirements to address first, like https://github.com/coreos/afterburn/issues/252.

**Comment by bgilbert** [comment]
This is still not currently planned, so I'll close this out for now.
