### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ashcrow** [coreos/afterburn#229]
There has roughly been [`the answer to life, the universe, and everything`](https://www.google.com/search?q=the+answer+to+life%2C+the+universe%2C+and+everything) commits since `4.1.0` was released. Recently https://github.com/coreos/afterburn/pull/224 merged and we'd like to start utilizing it. Could we get a new release cut for `afterburn`?

**Comment by rfairley** [comment]
:+1: will also update the Fedora `rust-afterburn` for the new release!

**Comment by lucab** [comment]
In progress at https://github.com/coreos/afterburn/pull/230.
