### ISSUE TITLE
config: consider sourcing options from files

### ISSUE THREAD

**Issue by lucab** [coreos/afterburn#252]
Afterburn is currently a one-short binary, entirely configured via command-line flags. This is on purpose to keep the complexity (both internally and externally) low.

Our service units are generally written to be easy to override via drop-ins, such as:
```
[Service]
Environment=AFTERBURN_OPT_PROVIDER="--provider foo"
```

However, if we start increasing the design complexity (e.g. with a daemon mode, https://github.com/coreos/afterburn/issues/228), we should consider sourcing file-based configurations.

This would be ideally done via [overlayed directories with dropins](http://docs.rs/liboverdrop), plus a simple and standard format (e.g. TOML).

**Comment by lucab** [comment]
This follows up to @cgwalters's suggestion from https://github.com/openshift/machine-config-operator/pull/964#issuecomment-511575675.

I'm not keen to go down this route **right now**, but this is pretty much a pre-requisite if we are doing big architectural changes like #228.

**Comment by prestist** [comment]
Currently we do not have a need for a config file for afterburn. We can revisit this if needed.
