### ISSUE TITLE
providers: Fetch instance-type metadata

### ISSUE THREAD

**Issue by zonggen** [coreos/afterburn#277]
# Feature Request #
Since in `fedora-coreos-pinger`, we need to fetch the instance type of cloud providers and I am trying to avoid too much duplicate code between fedora-coreos-pinger, Afterburn and Zincati, it would be great if we could fetch cloud instance type here.

## Environment ##

Apply to all cloud providers.

## Desired Feature ##

Fetch `cloud instance type` for all providers.

## Other Information ##
Link to related fedora-coreos-pinger issue: https://github.com/coreos/fedora-coreos-pinger/issues/30

**Comment by zonggen** [comment]
For different platforms, fetch `instance-type` as follows:
 - _AWS_: `GET meta-data/instance-type`
 - _Azure_: `GET metadata/instance/compute/sku?`
 - _Cloudstack_: `GET latest/meta-data/service_offering`
 - _DigitalOcean_: No similar type information provided ([link_to_metadata_schema](https://developers.digitalocean.com/documentation/metadata/#metadata-in-json))
 - _GCP_: `GET computeMetadata/v1/instance/machine-type`
 - _OpenStack_: `GET meta-data/instance-type`
 - _Packet_: `GET /metadata` and `plan` field from returned `json` file

**Comment by lucab** [comment]
@zonggen great investigation! I've forwarded a feature request to DigitalOcean to add that information to their metadata: https://github.com/digitalocean/api-v2/issues/182.
We can proceed without DO for the moment though.

**Comment by zonggen** [comment]
@lucab Thanks for creating the issue!
