### ISSUE TITLE
Update AWS metadata version

### ISSUE THREAD

**Issue by jhmartin** [coreos/afterburn#418]
# Feature Request #

## Environment ##

AWS

## Desired Feature ##
https://github.com/coreos/afterburn/blob/d8f74d5b6fd95dc201a406a68f33eb74b267dcbb/src/providers/aws/mod.rs#L65 references a fairly old AWS metadata version. To avoid confusion during support cases, consider using 2016-09-02 which is the most recent version specified at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html.

**Comment by lucab** [comment]
Self note: see similar thread on Ignition https://github.com/coreos/ignition/issues/989.
