### ISSUE TITLE
Support AWS IMDSv2

### ISSUE THREAD

**Issue by jhmartin** [coreos/afterburn#419]
# Feature Request #

## Environment ##

AWS

## Desired Feature ##

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html describes IMDSv2, which is a 2-step process to retrieving instance metadata. Enforcing IMDSv2 is beneficial for preventing attacks that trick an application into making requests to the IMDS and returning data such as the instance IAM credentials.  

A node can be launched to only support IMDSv2, so I suggest making afterburn compliant with this to enable the v2-only switch to be activated.

## Other Information ##
More details about IMDSv2:

https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Comment by zonggen** [comment]
Thanks for reporting!

Though I believe this is a duplicate of https://github.com/coreos/afterburn/issues/305

**Comment by jhmartin** [comment]
Oops, so it is!
