### ISSUE TITLE
ibmcloud: add support for SSH keys

### ISSUE THREAD

**Issue by lucab** [coreos/afterburn#472]
# Feature Request #

## Environment ##

Instances on `ibmcloud` platform (i.e. IBM cloud VPC gen2)

## Desired Feature ##

The `afterburn-sshkeys` service should work on this platform too, grabbing SSH keys from instance metadata and forwarding them to authorized keys.

**Comment by erlarese** [comment]
I have a fork started with a first pass at the changes for this here: https://github.com/coreos/afterburn/compare/master...erlarese:master

I think this issue could be assigned to me ?

**Comment by lucab** [comment]
Thanks, done! Feel free to open a PR whenever you are ready to get feedback, I'll happily go through it.
