### ISSUE TITLE
docs: add brief intro for platforms

### ISSUE THREAD

**Issue by bh7cw** [coreos/afterburn#490]
When I looked at the providers, there are `cloudstack`, `openstack`, `azurestack`(in the near future) confusing me in the beginning. Would help with brief intro or website links for platforms if anyone feels the same way.

**Comment by lucab** [comment]
In general it'd be good to stick to referencing https://docs.fedoraproject.org/en-US/fedora-coreos/platforms/ as the canonical source for platform IDs. There are a few platforms that came from Container Linux and that Afterburn still understands, though.

**Comment by bh7cw** [comment]
> In general it'd be good to stick to referencing https://docs.fedoraproject.org/en-US/fedora-coreos/platforms/ as the canonical source for platform IDs. There are a few platforms that came from Container Linux and that Afterburn still understands, though.

This https://docs.fedoraproject.org/en-US/fedora-coreos/platforms/ is clear. How do you think if summary those and platforms that came from Container Linux?

**Comment by lucab** [comment]
From an out-of-band conversation: we are trying to maintain developer documentation inline as rustdocs comments. Those can be viewed through `cargo doc --document-private-items --open`.
The `providers` module contains an (admittedly messy) list of of platforms with relevant outgoing links.

**Comment by bh7cw** [comment]
Thanks for clarifying. Based on this, I will close the issue.
