### ISSUE TITLE
Support IPv6 on AWS

### ISSUE THREAD

**Issue by jkroepke** [coreos/afterburn#726]
# Feature Request #

Currently afterburn only support IPv4 metadata, if the platform is AWS.

https://github.com/coreos/afterburn/blob/6e3f5452437cfcafc8c7abd6594b4e879a8bbc8d/src/providers/aws/mod.rs#L163-L164

Since [AWS announced IPv6 only subnets](https://aws.amazon.com/de/blogs/networking-and-content-delivery/introducing-ipv6-only-subnets-and-ec2-instances/) 

The IPv6 address can recived through meta-data.

```
http://169.254.169.254/latest/meta-data/ipv6
```
See also 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html

> The IPv6 address of the instance. In cases where multiple network interfaces are present, this refers to the eth0 device (the device for which the device number is 0) network interface and the first IPv6 address assigned. If no IPv6 address exists on network interface[0], this item is not set and results in an HTTP 404 response.

## Environment ##

AWS

## Desired Feature ##

Have `COREOS_EC2_IPV6` available in ignition configs.

## Other Information ##

The IPv6 meta-data is available in metadata version `2021-01-03`.
Consider to bump the default version
https://github.com/coreos/afterburn/blob/6e3f5452437cfcafc8c7abd6594b4e879a8bbc8d/src/providers/aws/mod.rs#L82
or use latest.

**Comment by bgilbert** [comment]
PR in #727.
