### ISSUE TITLE
Move away from `users` crate

### ISSUE THREAD

**Issue by jlebon** [coreos/afterburn#999]
It's deprecated:
- https://bugzilla.redhat.com/show_bug.cgi?id=2214213
- https://rustsec.org/advisories/RUSTSEC-2023-0040.html

It's been fork-adopted in https://crates.io/crates/uzers.

**Comment by decathorpe** [comment]
There's now also a security advisory open for `users` that causes crashes due to unreferencing unaligned pointers, which has been fixed in the `uzers` fork: <https://rustsec.org/advisories/RUSTSEC-2023-0059.html>
